name: Roman CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Java Setup
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Compile
      run: mvn compile
    - name: Test
      run: mvn test
    - name: Static Analysis
      run: mvn package